name: ASP.NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - uses: actions/checkout@v4

      # Setup .NET Core SDK (for .NET 6)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --no-restore

      # Run the project to check if it can start up
      - name: Check if server starts
        run: |
          dotnet run --project SimpleWebAppReact.csproj &
          echo $! > server.pid
          sleep 10
          kill $(cat server.pid) || echo "Server already stopped"
